### ISSUE TITLE
TypeError: elem.getAttribute is not a function

### ISSUE THREAD

**Issue by moltar** [taoqf/node-html-parser#100]
Version `3.0.0` (or `3.0.1`) seems to intro an error:

> TypeError: elem.getAttribute is not a function

```ts
const html = parse('...')

// happens here
html.querySelector('#foo')
```

**Comment by moltar** [comment]
```
      at Object.getAttributeValue (node_modules/node-html-parser/dist/matcher.js:11:17)
      at node_modules/css-select/lib/attributes.js:32:28
      at Object.findOne (node_modules/node-html-parser/dist/matcher.js:68:13)
      at node_modules/css-select/lib/index.js:117:27
      at Object.select [as selectOne] (node_modules/css-select/lib/index.js:64:16)
      at HTMLElement.Object.<anonymous>.HTMLElement.querySelector (node_modules/node-html-parser/dist/nodes/html.js:421:29)

...
```

**Comment by taoqf** [comment]
I need more details. [here](https://github.com/taoqf/node-html-parser/blob/main/test/85.js#L17) is an example of id selector, and the tests passed.

**Comment by olitoni** [comment]
I've got the same issue
```js
  let root = parse(data);
  let test = root.querySelectorAll('.observed');
  console.log(test[0].querySelector('.search'))
  
  //Returns:
  TypeError: elem.getAttribute is not a function
  ```

**Comment by olitoni** [comment]
Just tried, `2.1.0` works absolutely fine and returns the HTMLElement from the code above

**Comment by kika** [comment]
For me this error happens when there's *no* match for the selector.

**Comment by moltar** [comment]
> For me this error happens when there's *no* match for the selector.

Most likely the same for me. I'm checking for the existence of an element that I expect to be absent most of the time.

**Comment by kika** [comment]
I got around by using `querySelectorAll` and checking the length of the result. But I'd expect `querySelector` to return a falsey value, not a trap.

**Comment by taoqf** [comment]
> I got around by using `querySelectorAll` and checking the length of the result. But I'd expect `querySelector` to return a falsey value, not a trap.

May I know what is the html you parsed? I should do some tests and try to fix that.

> Just tried, `2.1.0` works absolutely fine and returns the HTMLElement from the code above

It will be easier for me to have the html.

I did some tests like that:

```js
const root = parse('<div class="a b"></div>');
root.querySelectorAll('a').length.should.eql(0);
should.equal(root.querySelector('a'), null);
root.querySelectorAll('.a').length.should.eql(1);
root.querySelectorAll('.b').length.should.eql(1);
should.notEqual(root.querySelector('.a'), null);
const nodelist = root.querySelectorAll('.a,.b');
nodelist.length.should.eql(1);
const div = nodelist[0];
root.querySelector('.a,.b').should.eql(div);
```

**Comment by taoqf** [comment]
I tried to fix the issue. If you guys won't give me any clue,  I will publish 3.0.2 several hours later.

**Comment by taoqf** [comment]
I think I fixed the issue. 3.0.2 published.

**Comment by taoqf** [comment]
Thank all of you.

**Comment by kika** [comment]
Yeeep, can confirm, now `querySelector` works as expected if there's nothing in the HTML that matches the selector.

**Comment by moltar** [comment]
Thanks @taoqf! 🙌🏼
