### ISSUE TITLE
querySelector and querySelectorAll just do not work

### ISSUE THREAD

**Issue by emyrTomos** [taoqf/node-html-parser#103]
a selector like 'li' to find all the list elements or 'a[href^="#"]' return empty arrays when elements satisfying the condition exist in the parsed node.

**Comment by taoqf** [comment]
What's the html like? 
which version are you using?

**Comment by emyrTomos** [comment]
i've moved to JSDOM which works just fine. I will come back and help your
project when I am done with this. Sorry to be abrupt x

**Comment by nonara** [comment]
Closing for housekeeping. If a reproducible test case is presented, we can reopen and address.
