### ISSUE TITLE
Kind of HTML errors that break the library

### ISSUE THREAD

**Issue by fctorial** [taoqf/node-html-parser#105]
The readme mentions that malformed errors might break the library. Can you give examples of html that might cause issues?

**Comment by taoqf** [comment]
You may need this <https://github.com/taoqf/node-html-parser/discussions/102>.

**Comment by fctorial** [comment]
@taoqf I was hoping for an example of html file that would break it.

**Comment by taoqf** [comment]
I am so sorry that I don't get much time on this.

**Comment by nonara** [comment]
Hi! Just wanted to add a quick answer on this.

There is currently one type of error which can cause an improper output, which is malformed HTML by not closing tags.

For example:
```html
<tagA>
<tagB>
<tagC>
<tagD>
</tagB>
</tagA>
```

Not properly closing a tag can cause issues in the parse output. This is something that I hope to address in the near future.
