### ISSUE TITLE
Changelog for v3.0.0 release?

### ISSUE THREAD

**Issue by niftylettuce** [taoqf/node-html-parser#108]
Might be nice to use `np` to do a nice release version with commit log.

**Comment by taoqf** [comment]
Thanks for your advice.

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/discussions/102

**Comment by taoqf** [comment]
np is a very nice releasing tool. so many thanks. @niftylettuce

**Comment by niftylettuce** [comment]
anytime!
