### ISSUE TITLE
Textarea renders erroneously

### ISSUE THREAD

**Issue by poisonborz** [taoqf/node-html-parser#109]
Textarea renders erroneously - not that only it doesn't use the separate close tag as in input (as I think it should), but it also misses `/>` closing tag.

```
const np = require('node-html-parser')
console.log(np.parse('<textarea id="input_3"></textarea>').toString())
```

Output: `<textarea id="input_3">`

**Comment by taoqf** [comment]
Yes, textarea is being treated as `selfclose` tag.

**Comment by poisonborz** [comment]
Textarea is not selfclosing https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea (even if it would be, the result above is not selfclosing either)

**Comment by taoqf** [comment]
Yeah, you are write. I will fix this.
