### ISSUE TITLE
Russian letters are not displayed

### ISSUE THREAD

**Issue by Keller18306** [taoqf/node-html-parser#113]
Chrome:
![image](https://user-images.githubusercontent.com/23178771/114306606-f2b37400-9ae4-11eb-83cc-d23bf617f993.png)
Parser:
![image](https://user-images.githubusercontent.com/23178771/114306623-0363ea00-9ae5-11eb-969b-5b7cd2a880d8.png)
![image](https://user-images.githubusercontent.com/23178771/114306637-0eb71580-9ae5-11eb-912a-bf18b21ff4cd.png)

**Comment by taoqf** [comment]
What was going on?

**Comment by Keller18306** [comment]
I specified extra headers and the site does not display the full version of the page

**Comment by taoqf** [comment]
I am really sorry I could not type the words shown in the images and I don't know anything about rassian.
I did tests like this:

```js
const html = '<div class="error mn-15-0-0" style="background: rgb(45, 45, 45);padding: 15px 20px;border-radius: 6px">\n                 Я указал Дополнительные заголовки, а сайт не отображает полную версию страницы - 200 (y bac - 3)\n</div>';
		const root = parse(html);
		root.toString().should.eql(html);
```

and it seems this test works very well.

**Comment by Keller18306** [comment]
Your package works great.  I was wrong.  As I realized that I had opened the topic in vain, I closed it.

**Comment by Keller18306** [comment]
> I specified extra headers and the site does not display the full version of the page

headers in the 'request' module
