### ISSUE TITLE
Require cycle warning for dist/nodes/html.js in version 3.1.5

### ISSUE THREAD

**Issue by denisgrenader** [taoqf/node-html-parser#114]
Require cycle: node_modules/node-html-parser/dist/nodes/html.js -> node_modules/node-html-parser/dist/parse.js -> node_modules/node-html-parser/dist/nodes/html.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle

**Comment by taoqf** [comment]
thank you, try v3.1.6, let me know if there are still issues.

**Comment by denisgrenader** [comment]
Thank you @taoqf -- cyclic warning gone in v3.1.6!
