### ISSUE TITLE
Leading/trailing single spaces not preserved in node text

### ISSUE THREAD

**Issue by nonara** [taoqf/node-html-parser#115]
## Issue

Example:
```html
<p>Hello <strong>world</strong>!</p>
```

This, unfortunately produces a TextNode whose text is `Hello` as opposed to `Hello<space>`
Examining the whole text of the parent `p` is `Helloworld!`

Unfortunately this is irreparably breaking `node-html-markdown`, as I have no way to determine whether there is a leading or trailing space.

see: https://github.com/crosstype/node-html-markdown/issues/9

## Proposal

In effort to be consistent with HTML spec, a single leading or trailing space should be captured, when present, in the text for any TextNode. 

I believe this proposal would be consistent with the behaviour of other parsers. However, if you decide against that route, an alternate proposal would be to add properties to the node `hasLeadingSpace` / `hasTrailingSpace`.

Would be interested to hear your thoughts on these. Thanks!

**Comment by serjant** [comment]
I have the same issue, it just trims leading and trailing spaces. Seems like the code which causes the issue is in `html.d.ts`:

`
return blocks.map((block) => {
			// Normalize each line's whitespace
			return block.join('').trim().replace(/\s{2,}/g, ' ');
		})
			.join('\n').replace(/\s+$/, '');	// trimRight;
`

**Comment by nonara** [comment]
@serjant Good find. Thanks!

Any maintainers around to weigh in on this? I'd propose a PR which removes the trim, effectively fixing the issue of removing legitimate leading/trailing whitespace. I'm happy to do this.

If there are any potential issues or side effects with this method, please let me know.

**Comment by serjant** [comment]
@nonara Likewise the **trim()** method is dangerous in that piece of code, because the **trim()** method removes whitespace from both ends of a string. Whitespace in this context is all the whitespace characters (space, tab, no-break space, etc.) and all the line terminator characters (LF, CR, etc.). [See the specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim)

**Comment by nonara** [comment]
@taoqf Just checking up on this. It's been close to a month without a reply, so I need to make a determination on what to do.

At this point there are two proposals - 

1. Remove trim() to correct the issue
2. Add `hasLeadingWhiteSpace` and `hasTrailingWhiteapace` properties to TextNode

I would suggest the former, as it complies with spec and makes the most sense.

I'm ready to do a PR for either with all necessary tests.

I don't mean to rush, but as this is a dependency, I will either need to write a new parser, fork this one, or (ideally) get a PR through. Whatever you decide is fine, but I would greatly appreciate a response to advise on which route I should take to get this fixed in my library.

Thanks!

**Comment by taoqf** [comment]
Sorry, I thought you would do a pr, now, I'll remove trim now.

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/releases/tag/v3.3.2

**Comment by nonara** [comment]
No worries. It's working well! Thanks!

**Comment by nonara** [comment]
Looks like I was wrong here. 

I didn't notice that I had been using `HTMLElement#removeWhitespace`, whose primary function is to remove empty whitespace nodes. 

Unfortunately, it also calls `trim()` on the text for each TextNode. This is a good thing, in that it removes repeating spaces, tabs, and line-breaks — these are often simply junk from multi-line HTML formatting. Unfortunately, for this case `trim()` itself, is a little bit too greedy, meaning that it will get rid of even a legitimate single non-breaking space inside the text node at the beginning or end of the text. 

Put more simply, it's overcorrecting in some scenarios. Here are some examples:

```html
<p>Hello <em>world!</em></p>` <!-- Desired: 'Hello world!' Actual: 'Helloworld!` -->
<p>Hello\n\r\r<em>world </em>!</p>` <!-- Desired: 'Helloworld !' Actual: 'Helloworld!` -->
<p>Hello\n\r\t<em>world   </em>!</p>` <!-- Desired: 'Hello world !' Actual: 'Helloworld!` -->
```

To correct this, I've made the following private method to replace the call to `trim()`. It performs the same action, with the exception that it will allow a single non-breaking space before and after the text, if one is present.

```ts
  /**
   * Trim all whitespace except single leading/trailing non-breaking space
   * @param text string to trim
   * @returns {string} trimmed value
   * @private
   */
  private trimTextNodeWhitespace(text: string): string {
    let i = 0;
    let startPos;
    let endPos;

    while (i >= 0 && i < text.length) {
      if (/\S/.test(text[i])) {
        if (startPos === undefined) {
          startPos = i;
          i = text.length;
        } else {
          endPos = i;
          i = void 0;
        }
      }

      if (startPos === undefined) i++;
      else i--;
    }

    if (startPos === undefined) startPos = 0;
    if (endPos === undefined) endPos = text.length - 1;

    const hasLeadingSpace = startPos > 0 && /[^\S\r\n]/.test(text[startPos-1]);
    const hasTrailingSpace = endPos < (text.length - 1) && /[^\S\r\n]/.test(text[endPos+1]);

    return (hasLeadingSpace ? ' ' : '') + text.slice(startPos, endPos + 1) + (hasTrailingSpace ? ' ' : '');
  }
```

Submiting PR in a moment.

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/releases/tag/v3.3.4
