### ISSUE TITLE
Switch from 'he' to 'lean-he' (or my forked 'lean-he-esm')

### ISSUE THREAD

**Issue by jogibear9988** [taoqf/node-html-parser#117]
As you only use decode from he, code size could be minimized using lean-he.

I've forked lean-he and created a typescript / esm version https://github.com/node-projects/lean-he

Cause when you use esm modules directly without transpiler, loading of the he imports will fail

**Comment by jogibear9988** [comment]
I've don this fix in my fork: https://github.com/node-projects/node-html-parser/commit/3a88678eea484448c1276f80fb7f41b51f1ed66a

**Comment by taoqf** [comment]
Thanks, he seems caused an serious memory leak, can you help?

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/issues/106

**Comment by jogibear9988** [comment]
No, I have not really looked deeply into he/lean-he. I only changed the files to .ts, fixed ES6 imports and published to npm
