### ISSUE TITLE
xxx.closest is not a function

### ISSUE THREAD

**Issue by BunnyMelody** [taoqf/node-html-parser#121]
I installed versioni 3.2.0, error occurs that `xxx.closet is not a function` , I read the code. It seems that function `closet` does not exist any longer.

Please check when available

**Comment by taoqf** [comment]
Sorry, do you mean `closest` ?
`closest` is added since v3.3.0
see <https://github.com/taoqf/node-html-parser/releases/tag/v3.3.0>
so if you used v3.2.0, you cannot use that method yet.

**Comment by BunnyMelody** [comment]
> Sorry, do you mean `closest` ?
> `closest` is added since v3.3.0
> see https://github.com/taoqf/node-html-parser/releases/tag/v3.3.0
> so if you used v3.2.0, you cannot use that method yet.

Ok, Thx
