### ISSUE TITLE
closing parent tag not correctly when html in attribute

### ISSUE THREAD

**Issue by KaninchenSpeed** [taoqf/node-html-parser#136]
The parser stops parsing the parent html tag when html tag in its attribute closes.

input html
`
<a testArg="<a>test</a>" secondArg="some_thing">some test content</a>
`

output html
`
<a testArg="<a>test</a>
`

**Comment by taoqf** [comment]
I am so sorry for that.
This issue could not be resolved by now.
It it an known issue as https://github.com/taoqf/node-html-parser/issues/51.
