### ISSUE TITLE
[Feature] Add / improve ESM support

### ISSUE THREAD

**Issue by hornta** [taoqf/node-html-parser#139]
I believe the README is wrong. It says to import the named export parse but it can't work because the file is CommonJS.

```
import { parse } from "node-html-parser";
         ^^^^^
SyntaxError: Named export 'parse' not found. The requested module 'node-html-parser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'node-html-parser';
const { parse } = pkg;
```

**Comment by nowaythatworked** [comment]
I just had the same error.  After a lot of trial & error I found following import which seems to work.
`import { parse as HTML, default as HTMLElement } from "node-html-parser/dist/nodes/html.js";`

**Comment by DanKaplanSES** [comment]
I have a typescript project and I am able to do both of these. 

@nowaythatworked  By the way, `default` does not equal `HTMLElement`. I think you probably meant to do this:

```import { parse, HTMLElement } ... ```

**Comment by Pomax** [comment]
Nice! As a potentially breaking change, releasing it as a new major version's probably a good idea.

**Comment by nonara** [comment]
Added in v5

**Comment by Pomax** [comment]
Hm, so I ran `npm i node-html-parser`, and package.json reports `"node-html-parser": "^5.0.0"`, but if I run my test code that starts with `import { parse } from "node-html-parser";` jest throws an import error:
```
    SyntaxError: The requested module 'node-html-parser' does not provide an export named 'parse'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:789:5)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:408:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:261:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.415 s, estimated 8 s
Ran all test suites matching /.\\test\\forms\\forms.test.js/i
```

**Comment by nonara** [comment]
We are not compiling a separate build for esm, as that is reportedly not the ideal way to handle it. 
Doing so can cause issues . Instead, we used a wrapper, which is the best route for making a cjs module work with esm.

See: https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1

It works on this end.

Check your `package.json` file to make sure it has `type: module` set.

For an example project, see `./test/assets/projects/esm`

**Comment by Pomax** [comment]
It very much does, I've been working on this library for the last 2 months and I haven't worked in CJS for much longer now ;)

**Comment by sw-yx** [comment]
still getting this error for what its worth.

```js
import {parse as nodehtmlparse} from 'node-html-parser';

//...
nodehtmlparse(content.trim().split('\n')[0])
```


Error: `parse is not a function`

**Comment by pilcrowOnPaper** [comment]
In SvelteKit, it works fine with `npm run dev` but I'm getting "parse is not a function" after `npm run build`.

**Comment by FractalHQ** [comment]
@pilcrowOnPaper I'm getting the same issue.  Named import works in dev but not in build, and default import works in build but not in dev.  Never seen this before.  Did you ever get it working in SvelteKit?

**Comment by pilcrowOnPaper** [comment]
@FractalHQ 

I gave up and used `parse5`, though I still prefer using `node-html-parser`

**Comment by nonara** [comment]
If you'd like to put together a repro I can clone, I will have a look. I have a gap of free time coming up for the first time in awhile, so I'll be able to look closer.

**Comment by Pomax** [comment]
@mattlehrer @FractalHQ if you're getting a similar issue, it's not this one: mine was fixed after cleaning cache and reinstalling, so it sounds like you want to file a new issue with more specific STR than I had, so it can be tracked independently of this closed issue =)

(also, so I stop getting notifications about an issue that got closed last October ;)
