### ISSUE TITLE
Compile error in Angular 9

### ISSUE THREAD

**Issue by viperphase1** [taoqf/node-html-parser#142]
After installing node-html-parser Angular cannot run the application because of this compile error:

`ERROR in node_modules/node-html-parser/dist/nodes/comment.d.ts:17:24 - error TS2693: 'string' only refers to a type, but is being used as a value here.
`

My tsconfig.json looks like this:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "module": "esnext",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "downlevelIteration": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}

```

Can this be fixed or do I need to change something about my set up?

**Comment by boukeversteegh** [comment]
You could try to solve this by upgrading typescript.

This worked for me, in a vue 2.x project.

`package.json`

```diff
-   "typescript": "^3.9.9",
+   "typescript": "^4.3.5",
```
