### ISSUE TITLE
New TS infers template literals which breaks for older TS

### ISSUE THREAD

**Issue by nonara** [taoqf/node-html-parser#143]
## Abstract

The current release seems to have somehow inferred template literal types as a return type for class methods in the compiled declaration files. In these cases, a `string` is the proper return type. Because template literal types are a newer feature, this is breaking compilation with typescript versions below the one which supports template literals.

## Example 
See: https://unpkg.com/node-html-parser@4.1.2/dist/nodes/comment.d.ts

Line 17 reads:
```ts
    toString(): `<!--${string}-->`;
```

What's odd is, when I run yarn build, this properly compiles to: `toString(): string`. It's possible that there was a bug with the version of TS that was used to compile the latest.

@taoqf Can you reset the project to the latest commit, wipe and reinstall node_modules, then run `yarn build` and let me know what line 17 says for `./dist/nodes/comment.d.ts` ?

## Proposed Solution

I think the solution here is:
1. Reinstall all modules 
2. Rebuild
2. Make sure there are no instances of the pattern: `` : ` `` (colon space backtick) in any `*.d.ts` files
   - Double check line 17 in `/dist/nodes/commend.d.ts` has type `string` to be sure
3. Publish patch version

## Related Issues
#120 
#142

**Comment by boukeversteegh** [comment]
I also suspect that the build was bad.

There are two funny aspects here related to the typescript version:


- compiling with TypeScript 3 generates `toString(): ``;` in `comment.d.ts` (assumption, not tested)
  - this generated code is accepted by TS4, but not by TS3
- compiling with TypeScript 4 generates `toString(): string;` (tested)
  - this generated code is accepted by both TS3 and TS4

So this is why upgrading to TS4 works, but it would be better if the _dist_ contained `:string` in the first place.

Also, I did not like being required to update my typescript to a next major version, just for 1 utility dependency.
If there are no deep reasons why it requires TS4, I would much prefer this library to be TS3 compatible.

**Comment by taoqf** [comment]
Sorry for late responding. I have rebuilt and released to 4.1.3.
Thanks for all your work.
https://github.com/taoqf/node-html-parser/release/tag/v4.1.3
https://unpkg.com/node-html-parser@4.1.3/dist/nodes/comment.d.ts
