### ISSUE TITLE
Why slug case and not camel case?

### ISSUE THREAD

**Issue by drachehavoc** [taoqf/node-html-parser#151]
The javascript pattern for methods, variables etc is camel case, but node-html-parser uses slug case.

my suggestion is to change to javascript pattern.

Before:
```javascript
root.set_content('<li>Hello World</li>');
```

After:
```javascript
root.setContent('<li>Hello World</li>');
```

**Comment by taoqf** [comment]
root.innerHTML = '<li>Hello World</li>'; may works for you.
use set_content when you use second param options.
