### ISSUE TITLE
Update querySelector type definition to return null

### ISSUE THREAD

**Issue by johnnyoshika** [taoqf/node-html-parser#157]
The TypeScript return type for `querySelector()`  is `HTMLElement` instead of `HTMLElement | null`. `querySelector()` can potentially return null if no elements are found. This will allow code that could throw a null reference exception to pass the type checker.

Relevant type definition:
```
    /**
     * Query CSS Selector to find matching node.
     * @param  {string}         selector Simplified CSS selector
     * @return {HTMLElement}    matching node
     */
    querySelector(selector: string): HTMLElement;
```

https://github.com/taoqf/node-html-parser/blob/2077d420b9cfde74e4f03639fa569b937735ebc5/src/nodes/html.ts#L383-L386

Can you set the return type to `HTMLElement | null`?

**Comment by nonara** [comment]
Good catch! Thanks for the heads up, Johnny.

**Comment by johnnyoshika** [comment]
@nonara Thank you for the great library! I depend on it extensively in my project.

**Comment by nonara** [comment]
Happy to help! @taoqf is the library's author, but I'm sure he'll be glad to hear that it's working well for you!

I have this and several other fixes in place in the following PR, but I'll also follow-up in this thread when we have a release ready.

- #161

**Comment by nonara** [comment]
Corrected in v5
