### ISSUE TITLE
"SyntaxError: The requested module 'node-html-parser' does not provide an export named 'parse'"

### ISSUE THREAD

**Issue by Pomax** [taoqf/node-html-parser#160]
Installed 4.1.5, running a project with `type: "module"` in package.json, and used the syntax `import { parse } from 'node-html-parser';` as per the README. Got this error.

**Comment by nonara** [comment]
Thanks for the report. This is a duplicate of https://github.com/taoqf/node-html-parser/issues/139

I have a fix ready. Should be released shortly.

**Comment by Pomax** [comment]
Nice! As a potentially breaking change, releasing it as a new major version's probably a good idea.

**Comment by nonara** [comment]
Yep. That's the plan. Will post a comment in this thread when it's released.
