### ISSUE TITLE
[Feature] Add getElementById()

### ISSUE THREAD

**Issue by Pomax** [taoqf/node-html-parser#165]
Given that there's support for `getElementsByTagName`, it would be nice if there was support for `getElementById`, too.

The main benefit would be that there are valid `id` attributes that you can't query-select, like `id` attribute with periods, which will not work as query selection string because periods will be treated as class markers. E.g. `<section id="attr.name">` cannot be query-selected using `#attr.name` as that will instead look for an element with `id="attr"` and `class="name"`.

**Comment by taoqf** [comment]
Added. v5.3.0. Thank all of you. Sorry for that I didn't added the method earlier. @nonara has already helped a lot.
