### ISSUE TITLE
Wrong nesting when parsing `a` inside another `a`

### ISSUE THREAD

**Issue by rndm2** [taoqf/node-html-parser#172]
Input: 
```
<!DOCTYPE html>
<html>
<body>
  <div id="1">

  <a id="s1">
    <a id="s2">2</a>
    <div id="ss1">2</div>
  </a>

  </div>
  <div id="2">
  </div>
</body>
</html>
```

Output: 
```
<!DOCTYPE html>
<html>
<body>
  <div id="1">

  <a id="s1">
    </a>
    <a id="s2">2</a>
    <div id="ss1">2</div>

  </div>
  <div id="2">

  </div>
</body>
</html>
```

I understand that `a` element inside another `a` is not allowed by HTML5 standard. 
But I believe parser should not make markup, it should parse it.

**Comment by nonara** [comment]
Thanks for the report!

We are actually handling nested A tags according to parser spec. To confirm, you can check this on www.astexplorer.net

Another way is to open chrome inspector and create a nested A tag in the source. When you click out of the edit box and inspect the DOM, you'll see that it's handled the same way.

Hope that helps!
