### ISSUE TITLE
rawAttrs didn't parse into attrs

### ISSUE THREAD

**Issue by yuklai** [taoqf/node-html-parser#177]
I have a HTMLElement node with the following string: 

`'href="query.asp?searchtype=ANY&query_type=queryCarrierSnapshot&query_param=USDOT&original_query_param=NAME&query_string=617356&original_query_string=FAUBER FREIGHTWAYS INC"'`

Any reason why?

**Comment by nonara** [comment]
Sorry to hear you're facing issues. Can you please paste the full html that causes this to happen?

**Comment by nonara** [comment]
Closing for housekeeping. Feel free to update if you have an example case, and I will reopen
