### ISSUE TITLE
HTMLElement class not compatible with typescript dom HTMLElement interface

### ISSUE THREAD

**Issue by viceice** [taoqf/node-html-parser#179]
Currently the `HTMLElement` isn't compatible with the global `HTMLElement` from the `dom` lib from typescript.
I'm not able to exclude the dom typings, because they are coming from a transitiv dependency

I would propose two solution:
1. rename `HTMLElement` class to not iterfere with interface
2. implement interface to be compatible

- ref https://github.com/renovatebot/renovate/pull/13233

**Comment by nonara** [comment]
Hi @viceice! Thanks for the report.

Unfortunately, naming collisions will tend to happen when there are different implementations which define the same sort of thing (ie. `Node`). This is generally not an issue, but I understand when global types are introduced it can pose an issue with TypeScript.

In these cases, it's generally best practice to simply use syntax such as you have or you can alias the type in the import statement.

Example: `import { HTMLElement as NhpHtmlElement } from `node-html-parser`

Hope that helps!

**Comment by viceice** [comment]
That don't help, as we can't use that import for esm modules 😕
