### ISSUE TITLE
Using `innerText` does not escape all HTML codes properly?

### ISSUE THREAD

**Issue by AgainPsychoX** [taoqf/node-html-parser#183]
While scrapping [OP.GG](https://euw.op.gg/summoner/userName=Azzapp), some text includes apostrophes (`'`).

In my example, I get `Vel&#039;Koz` instead of `Vel'Koz` no matter which method I use - `innerHTML` (shouldn't work, so it's okay), `rawText` (same), `innerText` (this definitely should work!).

Quick peek as image what is going on:
![image](https://user-images.githubusercontent.com/23557839/148702880-df6f272f-e868-4e66-a9a6-4faff232d71a.png)

Meanwhile in browser, it works as expected, or even better (as both `innerHTML` and `innerText` work):
![image](https://user-images.githubusercontent.com/23557839/148703025-c0f2d296-b1e6-4f9e-a340-f1d92e9167a4.png)

In my case, workaround is really easy: I just replace `&#039;` with `'`.

**Comment by nonara** [comment]
Thanks for the report! Please try with the `text` or `textContent` properties. Those decode HTML entities
