### ISSUE TITLE
Usage with worker threads

### ISSUE THREAD

**Issue by FabianL1** [taoqf/node-html-parser#184]
Hi there,

I'm a big fan of this library. Just wanted to know if there is a way to use this library with worker threads? That would be amazing.

Best,
Fabian

**Comment by nonara** [comment]
Hi Fabian! Thank you for the kind words.

I imagine it would work well with that. I've considered doing it, but have written an implementation yet. Off the top of my head, I would say create your threads with an instance of NHP in each, then setup a messaging system to send parse instructions and receive the results back.

Hope that helps, and I'd love to hear about it if you get it working.
