### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by po6ix** [taoqf/node-html-parser#189]
Details in here: https://blog.p6.is/writeups-for-hayyim-security-ctf-2022/#Solution-5

```
const sanitize = require('sanitize-html');
const { parse } = require('node-html-parser');

let html = "</a<a><a><a<a\x0ba ";
console.log(parse(sanitize(html)).outerHTML); // <a></a</a><a a></a>
```
The problem is node-html-parser parse the unclosing tag and `\x0b` wrongly.
And It can leads to a kindof mutation xss even with sanitized html string.

**Comment by nonara** [comment]
Thanks for the report. 

Quoting the readme:

> Per the design, it intends to parse massive HTML files in lowest price, thus the performance is the top priority. For this reason, some malformatted HTML may not be able to parse correctly

Considering that the library takes input HTML and produces a resulting set of nodes, XSS isn't really in the purview of this library. If taking user input, the user should take effort to properly validate input before using it. The library's purpose to to provide a minimally manipulatable DOM tree at minimal cost. 

Use of this library may be the right choice if there is a reasonable expectation of having valid HTML. If needs extend beyond this, using another library is advisable.
