### ISSUE TITLE
Bug: Error querySelector "pre code"

### ISSUE THREAD

**Issue by naptestdev** [taoqf/node-html-parser#190]
![image](https://user-images.githubusercontent.com/88878684/155360795-bc087f2f-23a1-46d7-a953-b7210a3bb9ed.png)

I'm selecting "pre code" but it doesn't return anything. Please fix the bug.

**Comment by taoqf** [comment]
You should add options like this:

```js
const dom = parse(html,{
	blockTextElements: {
		script: true,
		noscript: true,
		style: true,
		// pre: true,
		code: true
	}
});
```
