### ISSUE TITLE
Missing declaration file for ESM

### ISSUE THREAD

**Issue by f4Ro** [taoqf/node-html-parser#191]
When using ESM instead of CommonJS modules, TypeScript will look for an `index.d.ts` file in `/esm/index.d.ts` by default. 
As this file does not exist, TS gives an error for missing declarations.

A possible is overriding the declaration path in `tsconfig.json` which could look like this
```json
{
    "baseUrl": "node_modules",
    "paths": {
      "node-html-parser": ["node-html-parser/dist/index.d.ts"]
	}
}
```

**Comment by mondeja** [comment]
This is still an issue, why the change has been removed?
