### ISSUE TITLE
Bug: Parsing doesn't work with <script src="xx" /> in head 

### ISSUE THREAD

**Issue by mraxus** [taoqf/node-html-parser#195]
Tested with latest 5.2.0; nodeJs v14.19.0.

When running the following example I get 0 nodes found, when in fact there is one:

```
const { parse: HtmlParser } = require('node-html-parser');

var ls = `<html><head><script src="js/book.js" /><meta charset="UTF-8"/></head></html>`
console.log(HtmlParser(ls).querySelectorAll('meta').length);
```

If I change the `<script src="js/book.js" />` to `<script src="js/book.js"></script>` (or remove it), the code returns 1.

**Comment by taoqf** [comment]
`script` is not treated as self-cloing tag for now. I searched for the support, find [this](https://html.spec.whatwg.org/multipage/syntax.html#void-elements)

**Comment by taoqf** [comment]
try v5.4.0
