### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by dinhanhthi** [taoqf/node-html-parser#197]
I've tried your example and met this error. What I've tried,

```js
var HTMLParser = require('node-html-parser');
HTMLParser.parse('<ul id="list"><li>Hello World</li></ul>');
```

**Comment by taoqf** [comment]
Which version are you using? I could not find what was wrong.

**Comment by taoqf** [comment]
Which version are you using? I could not find what was wrong.

**Comment by dinhanhthi** [comment]
I used the latest. But that is no longer important (to me). Maybe only I have this problem.
