### ISSUE TITLE
structuredText with blank lines

### ISSUE THREAD

**Issue by woellij** [taoqf/node-html-parser#199]
Hi,

thanks for supporting this library.

I've stumbled upon an issue with structured text, where blank lines from html are ommitted in the `structuredText`.
Is there a way around that?

For example a element with that structure:
```
 b
    #text
    br
    br
    #text
    br
    br
```
results in only line-breaked text, but no blank lines.

Thanks for your response in advance.

**Comment by taoqf** [comment]
Would this help you?

```ts
html.replace(/\n/g, '');
```
