### ISSUE TITLE
Breaking changes when moving to 1.1.20

### ISSUE THREAD

**Issue by angas** [taoqf/node-html-parser#20]
index.ts no longer exports TextNode, CommentNode (or NodeType) leading to that something like this is no longer possible:

```
if (node instanceof TextNode && !node.isWhitespace) { ... }
```

**Comment by taoqf** [comment]
Sorry, I did know you need this, I will export them now.

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/commit/7ec7292f84a57636432b19e06c683e273c8faaf0
