### ISSUE TITLE
There is something unreasonable about the attributes selector

### ISSUE THREAD

**Issue by yeshaobin** [taoqf/node-html-parser#201]
```
<view
      v-stat.click="qwe123"
      data-mp="qwe123|click"
      class="received-list">
</view>
```

<img width="591" alt="image" src="https://user-images.githubusercontent.com/52816172/168342622-8295be74-62fa-48bc-88c7-535c9b53cdee.png">
It seems v-stat.click should be the attr but got v-stat and click .
i want to get the element by the "v-stat.click" attribute selector ,but got null . please help me

**Comment by Pomax** [comment]
That looks like jQuery code, not node-html-parser code?
