### ISSUE TITLE
How to extract just text from html Element

### ISSUE THREAD

**Issue by mknee40** [taoqf/node-html-parser#205]
I can't figure out how to just extract only the text from the element. 

For example:

```
    root.getElementsByTagName("p").map((elm) => {
        console.log(elm.text())
    });
```

throws an error `TypeError: elm.text is not a function` and the below returns the HTML elements in the child as a string e.g. `"text text text <a href="">text</a>"`:

```
    root.getElementsByTagName("p").map((elm) => {
        console.log(elm.toString())
    });
```

What I want is to extract only the text from the element.

**Comment by Carcraftz** [comment]
.innerText or .textContent
