### ISSUE TITLE
Omits `_` attribute used by Hyperscript

### ISSUE THREAD

**Issue by codepilotsf** [taoqf/node-html-parser#206]
In line 690 of nodes/html.ts, the regex disallows attributes starting with an underscore. This makes this lib incompatible with Hyperscript. (https://hyperscript.org). I forked your lib here: https://github.com/codepilotsf/node-html-parser-hyperscript

...but you may want to add the one underscore char to the regex so it works with Hyperscript. :-)

Thanks!

**Comment by taoqf** [comment]
Thank you very much for your advice.  I tried but faild with <https://github.com/taoqf/node-html-parser/issues/129>
