### ISSUE TITLE
node.d.ts in npm is old or broken?

### ISSUE THREAD

**Issue by IAkumaI** [taoqf/node-html-parser#210]
```Typescript
import {parse} from 'node-html-parser';

const root = parse('<div class="item">Some text</div>');

root.getAttribute('class'); // undefined. root - is some kind of virtual? ok
root.firstChild.getAttribute('class'); // error - Node does not has getAttribute method
root.querySelector('.item').getAttribute('class'); // Works, but I have to know selector. This is not a solution.
```

Hi. How can i get attribute from first root element?
I found https://github.com/taoqf/node-html-parser/blob/main/test/tests/quoteattributes.js#L26 is tests, but root.firstChild is Node, so it does not has getAttribute method.

I am using version 5.3.3 (latests from npm).

What am I doing wrong?

**Comment by IAkumaI** [comment]
Oh, I see. `getAttributes` do exists in Node.
But TypeScript think is don't, because of node.d.ts:

```
export default abstract class Node {
    parentNode: HTMLElement;
    abstract nodeType: NodeType;
    childNodes: Node[];
    range: readonly [number, number];
    abstract text: string;
    abstract rawText: string;
    abstract toString(): string;
    abstract clone(): Node;
    constructor(parentNode?: HTMLElement, range?: [number, number]);
    /**
     * Remove current node
     */
    remove(): this;
    get innerText(): string;
    get textContent(): string;
    set textContent(val: string);
}
```

Is it bug or old version or what?

**Comment by IAkumaI** [comment]
Well. It's just cause childNodes can be Node or HTMLElement and there is no way to know what is got.
So, this is not issue. Closed.

**Comment by taoqf** [comment]
By the way,

```ts
const root = parse('<div class="item">Some text</div>');
root.firstChild.getAttribute('class');  // should be `item`
```

should works.

**Comment by IAkumaI** [comment]
Yeah, it works.
It's just TypeScript showing the error "getAttribute does not exists on Node" without casting to HTMLElement.

But. If production you have to check `firstChild` is real HTMLElement, but not text-Node.

**Comment by taoqf** [comment]
Indeed.
> But. In production you have to check `firstChild` is real HTMLElement, but not text-Node.

**Comment by benwoodward** [comment]
> Well. It's just cause childNodes can be Node or HTMLElement and there is no way to know what is got. So, this is not issue. Closed.

If the childNodes can be either `Node` or `HTMLElement`, does that not mean the typing for `.firstChild`(and others) is incorrect?

```javascript
	/**
	 * Get first child node
	 * @return {Node} first child node <- should this not be `Node | HTMLElement`?
	 */
	public get firstChild() {
		return this.childNodes[0];
	}
```

https://github.com/taoqf/node-html-parser/blob/a439a96d3b7e934f13e5795f5d16ad4a2a10da3c/src/nodes/html.ts#L641

I'm puzzled by the Typescript errors I get when calling `.firstChild` or `.querySelector` on an `HTMLElement`:

```
  const targetElement: HTMLElement | null = startingElement?.firstChild // Type 'Node | null' is not assignable to type 'HTMLElement | null'
```

If I change its type to `Node | null`, I get an error on `.querySelector`

```
  const targetElement: Node | null = startingElement?.firstChild
  const firstChildElement = targetElement.querySelector('.specific-class') // Property 'querySelector' does not exist on type 'Node'
```

The code works fine because `startingElement?.firstChild` returns an `HTMLElement`, but Typescript thinks there's a problem, which suggests that the typings on `.firstChild` are incorrect.
