### ISSUE TITLE
Docs titles are hard to read

### ISSUE THREAD

**Issue by davestewart** [taoqf/node-html-parser#216]
Hi!

Thanks for the great lib. Using it very successfully.

My only comment is that the docs are hard to read on both there and NPM because of the classname prefix.

Could you do something to make it easier to read, perhaps change the format from:

### HTMLElement#trimRight()

Trim element from right (in block) after seeing pattern in a TextNode.

To

### trimRight()

Trim element from right (in block) after seeing pattern in a TextNode.

I think it's clear it's the HTMLElement; IMHO the tradeoff between explicitness and clarity doesn't serve the developer here.

Thanks,
Dave

**Comment by taoqf** [comment]
Thanks for your advice

**Comment by davestewart** [comment]
Nice! Much more readable, thank you ☺️
