### ISSUE TITLE
Fails to correctly parse attributes with dot(.) in the name

### ISSUE THREAD

**Issue by Devmond** [taoqf/node-html-parser#237]
`<b-button v-b-modal.modal-1>Launch demo modal</b-button>`

**v-b-modal.modal-1** is a vuejs directive. Per vuejs documentation, all vuejs code is valid html...not sure it is true.

The dot is apparently a valid character for an attribute but it fails to correctly handle it, instead it splits it into two attributes **v-b-modal** and **.modal-1**. Incidentally the browser's DOMParser doesn't handle it either.

**Comment by taoqf** [comment]
I am sorry this lib works not correct with vuejs for now, and I have not much time on this.

**Comment by callmephilip** [comment]
i think i managed to fix this see [this](https://github.com/callmephilip/node-html-parser/blob/handle-attrs-with-dots/test/tests/funkyattributes.js) 

@taoqf will you accept a PR?

**Comment by taoqf** [comment]
Of course I will. Sorry for keeping you waiting.
