### ISSUE TITLE
Broken HTML isn't parsed correctly

### ISSUE THREAD

**Issue by bennbollay** [taoqf/node-html-parser#241]
node-html-parser v6.1.5
Node v18.12.1

This may be a Works As Designed ticket, in which case feel free to close as appropriate.

The following HTML does not parse correctly:

```javascript
nhp = require('node-html-parser')
console.log(nhp.parse('<html><body id="main"><div></body></html>').toString())
// Output: '<html></html>'
// Expected: '<html><body id="main"><div></body></html>'
```

**Comment by nonara** [comment]
Thanks for the report. This is working as designed. Tradeoff for speed.

Per the readme:

> For this reason, some malformatted HTML may not be able to parse correctly, but most usual errors are covered (eg. HTML4 style no closing <li>, <td> etc).
