### ISSUE TITLE
get an error when parse vue html

### ISSUE THREAD

**Issue by samoyee** [taoqf/node-html-parser#243]
parse code
```
<div @click.stop>xxx</div>
```

it will become two attrs ```@click```, ```.stop```

I try to resolve the problem, change the code in `line:693 ./src/nodes/html.ts` 
```
const re = /([a-zA-Z()[\]#@$.?:][a-zA-Z0-9-_:()[\]#]*)(?:\s*=\s*((?:'[^']*')|(?:"[^"]*")|\S+))?/g;
```
```
const re = /([a-zA-Z()[\]#@$.?:][a-zA-Z0-9-_\.:()[\]#]*)(?:\s*=\s*((?:'[^']*')|(?:"[^"]*")|\S+))?/g;
```

add `\.`

**Comment by MusicDev33** [comment]
This is an HTML parser, valid Vue is not necessarily valid HTML. If you're looking for something that can parse Vue, I don't think this is the project. I'd recommend making a fork and continuing from there

**Comment by rschristian** [comment]
Vue and HTML are entirely separate things, so this seems to be correct behavior.
