### ISSUE TITLE
Line breaks are ignored by innerText

### ISSUE THREAD

**Issue by 1RandomDev** [taoqf/node-html-parser#249]
When using the `innerText` function on elements that contain line breaks (`<br>`) they get ignored in the output. A regular browser will convert them to \n characters.
For exmple `Hello<br>World` will result in `HelloWorld`, but expected is `Hello\nWorld`.

**Comment by zyrouge** [comment]
+1

**Comment by taoqf** [comment]
I am afraid I cannot see this behavior in chrome. my test code is like this
```js
const div = document.createElement('div');
div.innerHTML = 'Hello, <br>World!';
console.log(div.innerText);
```

**Comment by taoqf** [comment]
I add a new branch for this issue, but I don't think we should merge this, because chrome does the same.

**Comment by taoqf** [comment]
Merged.

**Comment by taoqf** [comment]
And thank you for feeding back.
