### ISSUE TITLE
Compile error: Cannot find name 'IterableIterator'.

### ISSUE THREAD

**Issue by NuclleaR** [taoqf/node-html-parser#250]
I created empty project using pnpm, added code from example and got error:
Cannot find name 'IterableIterator'.
26     values(): IterableIterator<string>;
                 ~~~~~~~~~~~~~~~~
Found 1 error in node_modules/.pnpm/node-html-parser@6.1.8/node_modules/node-html-parser/dist/nodes/html.d.ts:26

node: 20.5.1
pnpm: 8.5.1

node-html-parser: 6.1.8
typescript: 5.2.2

**Comment by taoqf** [comment]
Add a tsconfig.json to your project, make sure has lib "renext" in it.
