### ISSUE TITLE
Mermaid diagram in README.md is overflowing the call stack

### ISSUE THREAD

**Issue by dpilafian** [taoqf/node-html-parser#251]
Viewing the README.md file at:
https://github.com/taoqf/node-html-parser

hangs the browser in Safari and displays the following error in Chrome:
```
Unable to render rich display
Maximum call stack size exceeded
```

The error appears to be caused by two lines in the **Mermaid** diagram definition:

https://github.com/taoqf/node-html-parser/blob/6a816da48b9317fde3906e297c5f42c0734e8151/README.md?plain=1#L118

https://github.com/taoqf/node-html-parser/blob/6a816da48b9317fde3906e297c5f42c0734e8151/README.md?plain=1#L146

Commenting out the lines with `%%` enables the diagram to render without crashing.

**Comment by taoqf** [comment]
Thank you.
