### ISSUE TITLE
Breaking change upgrading to 1.2.x

### ISSUE THREAD

**Issue by sslotsky** [taoqf/node-html-parser#26]
Dependabot has been trying to upgrade me from 1.1.20 to 1.2.x, but each attempt has failed type checking on this code:

```ts
      const html = doc as HTMLElement;
      const title = html.querySelector('title');
      const content = html.querySelector('ufe-content');

      const forms = content.querySelectorAll('form');
```

The error I receive is:

```
    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    src/server/content.ts:54:29 - error TS2339: Property 'querySelectorAll' does not exist on type 'Node'.

    54       const forms = content.querySelectorAll('form');
```

In version 1.1.20, `html.querySelector('ufe-content')` returns the `HTMLElement` type. But with version 1.2.x, the error indicates that TypeScript thinks `querySelector` returns a `Node` instead.

Help is greatly appreciated!

**Comment by taoqf** [comment]
You can try 1.2.6, reopen this issue if you still have issues about this.
