### ISSUE TITLE
node_modules/node-html-parser/dist/nodes/comment.d.ts(18,1) | TS1128: Declaration or statement expected.

### ISSUE THREAD

**Issue by aguirrejuanse** [taoqf/node-html-parser#261]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `node-html-parser@3.3.6` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/node-html-parser/dist/nodes/comment.d.ts b/node_modules/node-html-parser/dist/nodes/comment.d.ts
index 82098ed..e33209b 100644
--- a/node_modules/node-html-parser/dist/nodes/comment.d.ts
+++ b/node_modules/node-html-parser/dist/nodes/comment.d.ts
@@ -14,5 +14,5 @@ export default class CommentNode extends Node {
      * @return {string} text content
      */
     get text(): string;
-    toString(): `<!--${string}-->`;
+    toString(): string;
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by taoqf** [comment]
Thanks, latest version looks fine.
