### ISSUE TITLE
Export NodeType again

### ISSUE THREAD

**Issue by isellsoap** [taoqf/node-html-parser#27]
In https://github.com/taoqf/node-html-parser/commit/cba17a7439e22baa8e3c9ffb152a0d4e6261ed5b the export of `NodeType` got removed (by accident?). I cannot upgrade to the latest version because of this.

It would be nice to have access to the enum and to be able to import it.

**Comment by isellsoap** [comment]
It still gets exported, but kinda hidden:

```
import NodeType from 'node-html-parser/dist/nodes/type'
```

Would be nice to be able to access `NodeType` as a named import from the root.

**Comment by taoqf** [comment]
Thank you for your report.
```ts
import { NodeType } from 'node-html-parser';
```
will be ok.
