### ISSUE TITLE
:contains() Case insensitive

### ISSUE THREAD

**Issue by servefast-cto** [taoqf/node-html-parser#276]
Is it possible to specify case insensitivity for `:contains()` query

[Example](https://codesandbox.io/p/sandbox/node-html-parser-demo-forked-tsd6w8?file=%2Fsrc%2Findex.js%3A6%2C4-6%2C20&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu8fbr3l00063j6gm715syqd%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu8fbr3l00023j6gjlifixgh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu8fbr3l00033j6g8uwy86j8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu8fbr3l00053j6gu5kuaukh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu8fbr3l00023j6gjlifixgh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu8fbr3l00013j6gug97i2qy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A4%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A20%257D%255D%257D%255D%252C%2522id%2522%253A%2522clu8fbr3l00023j6gjlifixgh%2522%252C%2522activeTabId%2522%253A%2522clu8fbr3l00013j6gug97i2qy%2522%257D%252C%2522clu8fbr3l00053j6gu5kuaukh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu8fbr3l00043j6ghdzlyz7b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clu8fbr3l00053j6gu5kuaukh%2522%252C%2522activeTabId%2522%253A%2522clu8fbr3l00043j6ghdzlyz7b%2522%257D%252C%2522clu8fbr3l00033j6g8uwy86j8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu8fbr3l00033j6g8uwy86j8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

This example selects text but i would also like to select Text as well is this supported since i know :contains() is not supported by css even

**Comment by taoqf** [comment]
Yes, you can use ':icontains' instead.

**Comment by servefast-cto** [comment]
@taoqf thank you good to know :)
