### ISSUE TITLE
Possibility to get Elements by Classname

### ISSUE THREAD

**Issue by wjanes** [taoqf/node-html-parser#278]
Hi
Is it possible to get elements by class name?
I have only found a method to find elements by tag name or find an element by id!

BR Wolfgang

**Comment by hakimio** [comment]
https://github.com/taoqf/node-html-parser?tab=readme-ov-file#queryselectorallselector

> Note: Full range of CSS3 selectors supported since v3.0.0.

**Comment by wjanes** [comment]
Ok thanks
