### ISSUE TITLE
querySelectorAll acting strange

### ISSUE THREAD

**Issue by WORMSS** [taoqf/node-html-parser#28]
```html
<dl>
  <dt>A</dt>
  <dd>B</dd>
  <dt>C</dt>
  <dd>D</dt>
</dl>
```
### Issue 1
```js
HTMLParser(contentAbove).querySelectorAll('dl > dt');
```
This fails to retrieve anything. I presume it's not exactly like the real query selector and can't understand direct descendants only and wants to do the more expensive any descendant. Fair enough, I can get around that. I can test the parent node and throw away that don't match.

### Issue 2
```js
HTMLParser(contentAbove).querySelectorAll('dl dt, dl dd');
```
This returns A, C, B, D but a browser `querySelectorAll` would return A, B, C, D
This one I am not able to easily code around. Require the correct order.

**Comment by taoqf** [comment]
Thanks for your report, I don't have much time on this recently. pr is welcomed.

**Comment by CluEleSsUK** [comment]
Further to this,
```
<div class="a b"></div>
```

cannot be retrieved with`HTMLParser(contentAbove).querySelectorAll(".a.b")` as one would expect

**Comment by HikariSenshi** [comment]
I also have similar problem. For example we have next structure:


`<ul item="111" id="list"><li>Hello World</li></ul>
`
1) only `ul` selector will work, or `[item]` for example
2) but `ul[item]` or `ul#list` returns null
