### ISSUE TITLE
`firstChild` and its docs seem to not match

### ISSUE THREAD

**Issue by olets** [taoqf/node-html-parser#285]
The docs say `firstChild` is `undefined` if the node has no children. https://github.com/taoqf/node-html-parser#firstchild

In fact, if I'm understanding correctly, `parse` wraps the provided markup in a tagless HTMLElement.

That's reasonable. It's a nice way of handling `parse('<div></div> <div></div>')`.

But it means, at least in the possibilities I've tried,

1. `firstChild` is never undefined
2. `firstChild` is the outermost element (not what I'd think of as a "child"), if the provided HTML has one outermost element.

(2) is sort of implied in the docs (https://github.com/taoqf/node-html-parser#usage)

```js
const root = parse('<ul id="list"><li>Hello World</li></ul>');

console.log(root.firstChild.structure);
// ul#list
//   li
//     #text
```

but it tripped me up: what I thought would be

```js
const root = parse('<div my-attribute></div>')
root.attributes
```

has to be

```js
const root = parse('<div my-attribute></div>')
root.firstChild.attributes
```

Repro: https://stackblitz.com/edit/node-html-parser-285?file=index.js

Don't know if the `firstChild` docs need more nuance, or if some other parts of the docs could use a warning (or even if this is a bug).

**Comment by taoqf** [comment]
the node `root` is a wrap node,some times the html would be like this:
```html
<li>Hello World</li>
<li>Hello World</li>
<li>Hello World</li>
```
Skip root, you will get the node you need.

**Comment by olets** [comment]
In your `li`s example, I can understand adding a wrapper, because there isn't a single top-level element. But in my example

```js
const root = parse('<div my-attribute></div>')

// don't do this
root.attributes

// do this
root.firstChild.attributes
```

it isn't intuitive for me, because there is a single top-level element.

I've searched some in the source and haven't found the wrapper logic. Is a wrapper always added if the outermost element isn't `html`?
