### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by luismramirezr** [taoqf/node-html-parser#32]
Is there an option to get a string minified version?

**Comment by taoqf** [comment]
Sorry I don't get you, what version?

**Comment by codinglabsdev** [comment]
I mean to minify the output of .toString()

**Comment by luismramirezr** [comment]
Sorry, I commented with another account

**Comment by taoqf** [comment]
Sorry, this just a parser, it would not do the minify thing for now, maybe you could try [uglify-js](https://www.npmjs.com/package/uglify-js).
