### ISSUE TITLE
To many results for querySelectorAll with tag.

### ISSUE THREAD

**Issue by xilokaine** [taoqf/node-html-parser#35]
bellow the code which get to many results for the table tag.

const request = require('request');
const HTMLParser = require ('node-html-parser');
request('http://nagiosadmin:nagiosadmin@nagioscore.demos.nagios.com/nagios/cgi-bin/status.cgi?host=all&limit=0', function (error, response, body) {
  const root = HTMLParser.parse(body);
  const table = root.querySelectorAll('table');
  console.log(table)
});

**Comment by taoqf** [comment]
Thanks.  try v1.2.13
