### ISSUE TITLE
nextElement

### ISSUE THREAD

**Issue by smmaxim1987** [taoqf/node-html-parser#41]
Good night!

Thanks you for create work!

Not work next element find :(

Example 
`html.querySelector('.pages .num span + a');` tag + tag = next element
or
for example found one element and want next element 
 **element1** and 
`element1.nextElementSibling ` = null

**Comment by taoqf** [comment]
Yes, it is not supported for now. pr is welcomed.

**Comment by niftylettuce** [comment]
👍

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/commit/d1cd9a7c38f9a1bb8c1ac7980c1e692479329a36

**Comment by taoqf** [comment]
v1.4.8
