### ISSUE TITLE
There's no declaration file for TypeScript

### ISSUE THREAD

**Issue by NoamKoKo** [taoqf/node-html-parser#43]
Is that on purpose?
Having proper types can be very very helpful.
### Versions
**node-html-parser:** 1.2.16
**Node:** 14.0.0
**npm:** 16.14.4
**VSCode:** 1.44.2
**typescript:** 3.7.5

**Comment by taoqf** [comment]
Which version are you using?

**Comment by NoamKoKo** [comment]
Oh, right, I really forgot adding versions information.

**node-html-parser:** 1.2.16
**Node:** 14.0.0
**npm:** 16.14.4
**VSCode:** 1.44.2
**typescript:** 3.7.5

**Comment by taoqf** [comment]
Sorry for my response not in time. I checked 1.2.16, and there is type declaration files in dist/index.d.ts. maybe you could try another version? or could you create a demo?
