### ISSUE TITLE
Typescript types seem to be incorrect

### ISSUE THREAD

**Issue by rschristian** [taoqf/node-html-parser#47]
Trying to follow the little example in the ReadMe, it seems like your type definitions are off, as it certainly won't compile. The following code...

```
const root = parse('<ul id="list"><li>Hello World</li></ul>');
console.log(root.firstChild.structure);
```

...results in the following error...

```
index.tsx:31:33 - error TS2339: Property 'firstChild' does not exist on type '(TextNode & { valid: boolean; }) | (HTMLElement & { valid: boolean; })'.
  Property 'firstChild' does not exist on type 'TextNode & { valid: boolean; }'.

31             console.log(content.firstChild.structure);
```

Using Node-HTML-Parser v1.2.17

**Comment by taoqf** [comment]
I am so sorry that we do not have firstChild(and many attributes and methods) defined in TextNode.I have changed the definition in 1.2.18. let me know if you still have issues.

**Comment by RyanChristian4427** [comment]
Well one step closer, but `structure` does not exist on `Node`. It will need to be added [here](https://github.com/taoqf/node-html-parser/blob/master/src/nodes/node.ts) for someone to follow even the second line of the demo.

**Comment by taoqf** [comment]
It is not enough if only definition defined.see https://github.com/taoqf/node-html-parser/blob/master/src/nodes/html.ts#L228

**Comment by alogim** [comment]
@rschristian @taoqf If you want to follow the README with TyepScript, write the following:

```
import { HTMLElement, parse } from 'node-html-parser';
const root: HTMLElement = parse(this.authorisation.description.description);
console.log((root.firstChild as HTMLElement).structure);
```
Since HTMLElement is overwritten by this package, you need to import the one which has been overwritten and not the base one.
