### ISSUE TITLE
html 5 escapes are returned in .text

### ISSUE THREAD

**Issue by TiPPeX2** [taoqf/node-html-parser#48]
from the interface I see:
    /**
     * Get unescaped text value of current node and its children.
     * @return {string} text content
     */
    get text(): string;

How do you get HTML5 encoding unescaped?
Since it didn't work on my test.
i.e:
The king&#39(;)s hat is on fire!

to
The king's hat is on fire!

**Comment by taoqf** [comment]
It seems works fine. maybe you could try the latest version.
