### ISSUE TITLE
Is there a way to append just a Text Node 

### ISSUE THREAD

**Issue by NiaLikesCode** [taoqf/node-html-parser#50]
I see there is an ability to append an HTMLNode to children Nodes but is there a way to do that with TextNodes as well?

**Comment by taoqf** [comment]
I am afraid I don't get you. You mean `insertAdjacentHTML`?

**Comment by taoqf** [comment]
I could not figure out  how to append children to textnode.

**Comment by NiaLikesCode** [comment]
as I understand insertAdjacentHTML allows me to insert an HTMLNode in a certain position inside a parent's childNodes list
I wanted to know if there was an equivalent for inserting an adjacent Text Node

**Comment by taoqf** [comment]
You mean [this](https://github.com/taoqf/node-html-parser/commit/83706163bf504615073cf2741675c8f44b5a4b44)?

**Comment by NiaLikesCode** [comment]
ah yes I believe so 
ok so that answers my question
thank you
