### ISSUE TITLE
removeChild(node: Node) does not actually remove the child node.

### ISSUE THREAD

**Issue by gzimh** [taoqf/node-html-parser#52]
HTMLParser.HTMLElement.removeChild(node: Node) does not actually remove the child node.

Method description:
`Remove Child element from childNodes array`

Expected Result: The child node will be removed from the childNodes array

Actual Result: The childNodes array is not affectd

**Comment by taoqf** [comment]
Maybe you passed a node is not really it's child. Good luck!
