### ISSUE TITLE
parser fails to keep script element child nodes

### ISSUE THREAD

**Issue by niole** [taoqf/node-html-parser#55]
failing repro:
```js
const page = "<!DOCTYPE html><html lang="en"><head></head><body><script id="storeFinder" type="application/json">{"key":true}</script></body></html>"
const root = parse(page);
const storeFinder = document.querySelector("#storeFinder");
console.log("store finder exists", storeFinder !== null);
console.log("no child nodes are kept", storeFinder.childNodes.length === 0);
```

Expectation: the parser keeps the child nodes of script tags as text nodes, like how the parser keeps text nodes of `divs`

**Comment by peterlerche** [comment]
I have the same issue. Any idea how to work around it ?

**Comment by peterlerche** [comment]
Have just discovered that it is not just affect <script> but also <code> elements

**Comment by Zauberfisch** [comment]
This bug might also apply to style tags

**Comment by taoqf** [comment]
adding option `script:true` may help you. <https://github.com/taoqf/node-html-parser/issues/45>. I will do some tests if I have time.
