### ISSUE TITLE
how do I select the middle td?

### ISSUE THREAD

**Issue by working-name** [taoqf/node-html-parser#59]
Here's my .structure 
```
'tr
  td
    div
      span
        #text
      p
        #text
      p
        #text
  td
    #text
  td
    span
      #text'
```
Trying to get the second `td`. I tried all I could think of... no go. Is this even implemented?

**Comment by HP4k1h5** [comment]
i think you want something like 
```javascript
root.querySelector('tr td:nth-child(2)')
```

**Comment by taoqf** [comment]
I would say maybe you should querySelectorAll, and then filter the result array. Good luck.
