### ISSUE TITLE
Errors with TypeScript 4.x

### ISSUE THREAD

**Issue by isellsoap** [taoqf/node-html-parser#61]
The breaking change “Properties Overridding Accessors (and vice versa) is an Error” in the [TypeScript 4 release](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-rc/#properties-overridding-accessors-and-vice-versa-is-an-error) throws a few errors in the package.

<img width="1120" alt="Bildschirmfoto 2020-08-24 um 12 58 05" src="https://user-images.githubusercontent.com/477474/91037552-7a597a80-e609-11ea-9ef3-b2daf27d7c59.png">

**Comment by taoqf** [comment]
v 1.2.21 is published.
