### ISSUE TITLE
Why is the "innerText" attribute renamed to "rawText"?

### ISSUE THREAD

**Issue by benwinding** [taoqf/node-html-parser#67]
In the documentation, it's noted that _ELEMENT_.**rawText** behaves just like _ELEMENT_.**innerText**. Why not use the same attribute?? 

https://www.npmjs.com/package/node-html-parser#htmlelementtext

Then scripts that run in the browser (for testing) will also run in this environment...

Anyway, thanks for a great library!

**Comment by taoqf** [comment]
Ah, I think we may get answer from [the author](https://github.com/ashi009).
Thank you for your support. but I think we could add another attribute `innerText'. If I have time I will do this. and pr is also 
welcomed.

**Comment by benwinding** [comment]
Nice, thanks @taoqf !
