### ISSUE TITLE
element.getAttribute return undefined

### ISSUE THREAD

**Issue by quillcraft** [taoqf/node-html-parser#70]
I try to read an attribute, I get 'undefined'.

```
function extractData(body) {
	const html = HTMLParser.parse(body);
	const date = html.querySelector('cv-stats-virus');
	console.log(date.getAttribute(':charts-data'));
}
// undefined
```

**Comment by roeniss** [comment]
same

**Comment by taoqf** [comment]
Sorry I don't get the point. what's the html like?

**Comment by NickieNay** [comment]
I get the same behavior with html like:
`<meta property="og:type" content="product">`

I cannot get the property attribute of this element - it returns undefined. If I set an attribute with `setAttribute('test', 'value')` then I'm able to retrieve `test`. 

But, it replaces rawAttrs with 'test="value"'. Any subsequent setting of attributes doesn't replace rawAttrs, but adds to it.

**Comment by taoqf** [comment]
@NickieNay I am so sorry, I add [a test](https://github.com/taoqf/node-html-parser/commit/bac1b5ba531a09e3e226cc7c376df215981399c4) for this, and find no clue at all.

**Comment by Stanoja** [comment]
Hi @taoqf,
The issue is still present in a similar variant.

This html:
`<button type="submit" name="add-to-cart" value="12121" data-product_id="12121" data-quantity="1" class="some_add_to_cart_class other_add_to_cart_class third_add_to_cart_class random_other_class  button alt">My button</button>`

Returns these attributes:
`{
  type: 'submit',
  name: 'add-to-cart',
  value: '12121',
  'data-product': '',
  'data-quantity': '1',
  class: 'some_add_to_cart_class other_add_to_cart_class third_add_to_cart_class random_other_class'
}`

Following this, there's no way to actually get the attribute `data-product_id="12121"`.

**Comment by NickieNay** [comment]
I was using Axios to get a page's HTML, and it returned in this format.
```
data= '\n\n<!doctype html>\n<html class="no-js" lang="en">\n\n<head> \n\n<meta property="og:type" content="product" />\n</head></html>'
```

But, I did a test of my own, and it parses it fine and gives the expected output:
```
const data = '\n\n<!doctype html>\n<html class="no-js" lang="en">\n\n<head> \n\n<meta property="og:type" content="product" />\n</head></html>';
const root = parse(data);
const metas = root.querySelectorAll('meta');
console.log(metas[0].getAttribute('property');

// output: 'og:type'
```

I have no idea why we're having this issue.

**Comment by Stanoja** [comment]
@NickieNay I am using axios as well, did you manage to solve the issue?
What I did as a workaround is parsing it with regex since the attributes were not constructed properly in my example:
```
const match = /data-product_id="(\d+)"/.exec(myButtonElement.rawAttrs);
return match[1];
```

What I can suggest is to print the `node._rawAttrs` and see the key-value pair of attributes.

**Comment by taoqf** [comment]
> Hi @taoqf,
> The issue is still present in a similar variant.
> 
> This html:
> 
> ```
> <button type="submit" name="add-to-cart" value="12121" data-product_id="12121" data-quantity="1" class="some_add_to_cart_class other_add_to_cart_class third_add_to_cart_class random_other_class  button alt">My button</button>
> ```
> 
> Returns these attributes:
> 
> ```
> {
>   type: 'submit',
>   name: 'add-to-cart',
>   value: '12121',
>   'data-product': '',
>   'data-quantity': '1',
>   class: 'some_add_to_cart_class other_add_to_cart_class third_add_to_cart_class random_other_class'
> }
> ```
> 
> Following this, there's no way to actually get the attribute `data-product_id="12121"`.

I tried with chrome, attribute name with `_` is ok, so I will improve this.

**Comment by taoqf** [comment]
> I was using Axios to get a page's HTML, and it returned in this format (edited to have only head with one meta tag).
> 
> ```
> data= '\n\n<!doctype html>\n<html class="no-js" lang="en">\n\n<head> \n\n<meta property="og:type" content="product" />\n</head></html>'
> ```
> 
> But, I did a test of my own, and it parses it fine and gives the expected output:
> 
> ```
> const data = '\n\n<!doctype html>\n<html class="no-js" lang="en">\n\n<head> \n\n<meta property="og:type" content="product" />\n</head></html>';
> const root = parse(data);
> const metas = root.querySelectorAll('meta');
> console.log(metas[0].getAttribute('property');
> 
> // output: 'og:type'
> ```
> 
> I have no idea why we're having this issue.

Could you test with the whole page? or past html here, I can do the test as well.

**Comment by taoqf** [comment]
closing as no response.
