### ISSUE TITLE
<style> tag is not parsed correctly

### ISSUE THREAD

**Issue by garysui** [taoqf/node-html-parser#71]
```
<style>
  .my-class {
    font-size: 90%;
  }
</style>
```

toString() will not get content of the style tag

**Comment by taoqf** [comment]
Add option style:true may help you. see <https://github.com/taoqf/node-html-parser#parsedata-options>

**Comment by taoqf** [comment]
But I'm considering remove option `script`, `style` and `pre`.

**Comment by taoqf** [comment]
If this change break something ,please let me know.

**Comment by nonara** [comment]
@taoqf Does this mean that style is now always parsed and cannot be skipped or that it is not parsed?

**Comment by taoqf** [comment]
Yes.

**Comment by taoqf** [comment]
@nonara Do you need it to be skipped?

**Comment by nonara** [comment]
For our use case, we're converting HTML to markdown, and speed is essential, so skipping style was set for performance reasons. 

We can skip it on our end during walking the nodes, but it would probably be more performant to be able to skip during parse.

It's your call! 

My 2 cents is it might be a good idea to add the two options back in, set default to false, and bump the patch version. Right now, anyone using those options will find their builds broken with this version.

After, you can enable the `pre` and `style` options by default and bump the major version.

**Comment by taoqf** [comment]
https://github.com/taoqf/node-html-parser/commit/d7a8c292cf81041053ebdcdc7535d084af6c2f89
