### ISSUE TITLE
Option to parse ONLY HTML tags

### ISSUE THREAD

**Issue by VladimirMikulic** [taoqf/node-html-parser#73]
Hi! First of all, I would like to thank you for this package.
It does work well except for one issue.

Let's say we have C code like this:
```c
#include <stdio.h>
```

After I parse it with this package, `.text` property returns `#include ` without <stdio.h>.
I suspect that is because package treats <stdio.h> as a HTML tag, but it's not.
It's the syntax for importing libraries in C.

Could we have an option where the plugin would strictly parse HTML tags (span, div etc.) without parsing "custom" tags?

Thank you.

**Comment by taoqf** [comment]
```html
#include &ltstdio.h&gt
```
I think we should replace `<` with `&lt` and `>` with `&gt`.

**Comment by VladimirMikulic** [comment]
Thanks for your reply @taoqf. Should I replace `</>` with `&lt/&gt`, respectively before running my code through your HTML parser?

**Comment by taoqf** [comment]
Yes.

**Comment by VladimirMikulic** [comment]
That's a very neat solution. Thank you so much!
