### ISSUE TITLE
CSS Selector :nth-child() return null (not implemented ?)

### ISSUE THREAD

**Issue by mathias22osterhagen22** [taoqf/node-html-parser#74]
```html
<tbody>
   <tr class="odd">
      <td>13/10/2020</td>
      <td>
         Cell2
      </td>
      <td>
         <a href="/mjrcs-32432">Cell3</a>
      </td>
      <td>
         <a target="_blank" href="/5z9LX1.pdf" ><img alt="PDF File" src="/mjrcs-resa/images/v2/icone_pdf.gif"></a>
      </td>
      <td>
         <a target="winzip" href="/33WzKc.zip"><img alt="ZIP File" src="/mjrcs-resa/images/v2/icone_pdf_archive.gif" height="16" ></a>
      </td>
      <td>
         <a target="_blank" href="/3QhZGq.xml"><img alt="XML file"  src="/mjrcs-resa/images/v2/icone_xml.gif" height="16" ></a>
      </td>
      <td>
      </td>
   </tr>
```

**Expected:** 
`document.querySelector('table tbody tr td:nth-child(6) a').href`
> `/3QhZGq.xml` 

**Result:** 
`document.querySelector('table tbody tr td:nth-child(6) a').href`
> `null` 

**Screenshoot: **
![image](https://user-images.githubusercontent.com/60438474/95995741-2eb99500-0e32-11eb-9b61-dd676323b972.png)

**Comment by taoqf** [comment]
I'm very sorry the selector is not supported yet.

**Comment by mathias22osterhagen22** [comment]
Thank you for your answear, Is ':not' not implemented as well ?

**Comment by taoqf** [comment]
> Thank you for your answear, Is `:not` not implemented as well ? (and `[href*="partOfUrl"]` seems not working too)

no.
