### ISSUE TITLE
Uppercase CLASS (with capitals) is not detected

### ISSUE THREAD

**Issue by DenizBasgoren** [taoqf/node-html-parser#75]
`parser.parse('<div CLASS="a"></div>').querySelectorAll('.a')`
The code above returns [ ].

**Comment by taoqf** [comment]
Please use replace `CLASS` with `class`
```js
parser.parse('<div CLASS="a"></div>'.toLowerCase()).querySelectorAll('.a')
```

**Comment by DenizBasgoren** [comment]
This is a workaround, however HTML states that tags and attributes are case insensitive. Please correct the behavior of your parser.

**Comment by taoqf** [comment]
Thanks for your report,

**Comment by DenizBasgoren** [comment]
Thanks
