### ISSUE TITLE
PRE block child nodes not parsed & DOCTYPE not recognized

### ISSUE THREAD

**Issue by nonara** [taoqf/node-html-parser#78]
Hi! First, thanks for the great work on this library! This is truly the fastest and best out there.

I needed a lightning fast html-to-markdown library, and everything out there was extremely slow. With the help of `node-html-parser`, I was able to [write something](https://github.com/crosstype/node-html-markdown) that blazes through it! (I'll be writing a readme soon, but it is a full release)

In the process, I discovered two issues, which I'll detail below.

## PRE blocks don't parse children

In pre-formatted elements, contents are always being treated as text, so child-nodes do not get parsed.

This causes an issue for multi-line code blocks. Per spec, a multi-line code block is `<code>` wrapped in `<pre>`. (see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code#Notes)

The following treats `<code ... >` as a text node, where spec behaviour is to allow HTML child nodes within `pre`
```html
<pre>
  <code class='language-javascript'>
    console.log('hello');
  </code>
</pre>
```

You can see how we workaround this, here: https://github.com/crosstype/node-html-markdown/blob/master/src/config.ts#L79-L89

## DOCTYPE is parsed as a text node

`<!DOCTYPE ...>` nodes are being parsed as text nodes. I think the desired behaviour here would be to simply ignore the node.

To work around this, we're temporarily replacing them ahead of time. (see: https://github.com/crosstype/node-html-markdown/blob/master/src/main.ts#L40-L42)

## Side-note

This and another of my libraries broke after a recent yarn install, due to the fact that the options we passed were no longer valid. We were specifying `{ pre: true, style: false }`

Not a major issue, but if you're following semver, changing public API options is generally considered a breaking change, as it could cause projects which use it as a dependency to fail to compile.

Thanks again for the great work, and I hope you have a good day!

**Comment by taoqf** [comment]
1. tag `pre` was defined as [`BlockTextElements`](https://github.com/taoqf/node-html-parser/blob/master/src/nodes/html.ts#L651), I don't know what will happen if I remove it from blocktextelements. maybe it will slow down the speed in most use cases, maybe not. anyway, I have added an option `blockTextElements` to resolve this and I hope this would not cause much trouble.
1.It will break something if I ignore tag `doctype`.someone may use this parse a whole page, and convert back to text after they changed something.so I'm sorry I can't add this yet.

**Comment by nonara** [comment]
> I have added an option blockTextElements to resolve this and I hope this would not cause much trouble.

That will work. Thanks for such a fast response!

>  It will break something if I ignore tag `doctype`. ...

That makes complete sense. I agree that it definitely should not be ignored, then.

I should have probably clarified the problem better.

There are three types of nodes that the parser can create during parsing.

1. Element Node
2. Text Node
3. Comment Node

Anything that is an HTML element is an Element Node. Anything that is plain text is a Text Node.

In the case of `<!DOCTYPE html>`, HTML parsers recognize this as an Element Node (nodeType = 1). This would have `tagName` = `!DOCTYPE`.

What's happening in this parser is, we get a Text Node where the caption is `<!DOCTYPE html>`. I don't believe that this would be desirable behaviour, and it is inconsistent with other HTML parsers. So I believe that this qualifies as a bug.

> I don't know what will happen if I remove it from blocktextelements. maybe it will slow down the speed in most use cases, 

In terms of performance, you'd likely see little to no difference. The reason I'd argue for changing it is because an HTML parser should comply with HTML spec. In the case of `pre`, child elements are allowed and not considered text. If it weren't for `<pre><code></code></pre>`, it may not matter as much, but multi-line code blocks are pretty common.

But I want to clarify that I'm not trying to nit-pick. Your `blockTextElements` solution will work fine for me! 

I decided that I'd leave the comment here because due to the difference in this and HTML spec, there is a chance that duplicate issues may be opened. So if in the future this is something you want to look into. I'd be interested in following the conversation.

**Comment by nonara** [comment]
As a side note, if you'd ever like help in maintaining this, feel free to send a ping any time. I do a lot of work with parsers and compilers. Thanks again for the fast response and fix!

**Comment by sebromero** [comment]
Hi all! I'm using node-html-parser 2.1.0 with the blockTextElements to get the nodes from `code` tags inside `pre`. However, the classNames attribute of those code tags is empty. Is that the expected behaviour?
```
parser.parse(this.rawHTML, {
    blockTextElements: {
        script: true,
        noscript: true,
        style: true,
        pre: false
      }
});
```

**Comment by taoqf** [comment]
@sebromero Yes. If you want get code inside pre, remove `pre` from blocktextelments, and add add `code`. like this.

```ts
parser.parse(this.rawHTML, {
    blockTextElements: {
        script: true,
        noscript: true,
        style: true,
        code: false
      }
});
```

**Comment by sebromero** [comment]
@taoqf That worked perfectly, thank you! It wasn't fully clear to me from the documentation how to use the config object. I thought those were boolean flags on whether or not to parse those elements as blockTextElements. 😅

**Comment by dlemfh** [comment]
Hi, from my tests on using this library

`parse(SOME_HTML_TEXT, { blockTextElements: { pre: true }})` causes
- the `pre` element to be an ELEMENT_NODE
- children within `pre` to be a single TEXT_NODE

`parse(SOME_HTML_TEXT, { blockTextElements: { }})` causes
- the `pre` element to be an ELEMENT_NODE
- html tags within `pre` to be parsed as ELEMENT_NODEs as well

`parse(SOME_HTML_TEXT, { blockTextElements: { pre: false }})` causes
- the `pre` element to be an ELEMENT_NODE
- and the `pre` element is parsed to have no children at all

Would I be correct to assume this is the intended behavior? If there's anything I'm missing I'd appreciate any heads up!

**Comment by nonara** [comment]
@dlemfh It looks like the logic is that the _presence_ of the key indicates that it's block text, and the value (true or false) indicates whether its contents should be ignored or preserved.

In other words, it seems that it's behaving as expected. If you want to not treat `pre` as block text, you should omit it entirely from the object.

**Comment by dlemfh** [comment]
@nonara Seems that way. Thanks!!

**Comment by bogdanionitabp** [comment]
But it seems you must still pass an empty object as the blockTextElements, otherwise the pre elements will not be parsed. If this was intended, then it's too confusing, otherwise it's too buggy.
