### ISSUE TITLE
es6 module package

### ISSUE THREAD

**Issue by jogibear9988** [taoqf/node-html-parser#79]
Is it possible to release a ES6 package?

If I try to use the package directly in browser I get this error:

![image](https://user-images.githubusercontent.com/364896/97230426-2ff7a400-17da-11eb-929f-65f2fc8f6234.png)

**Comment by taoqf** [comment]
Sorry I can't see the image in my country, would you please past the error text?

**Comment by jogibear9988** [comment]
in the browser i get "exports is not defined"

I've created a pull request, wich compiles to "esm" in the esm subfolder
