### ISSUE TITLE
node-html-parser v1.4.2: Object prototype may only be an Object or null

### ISSUE THREAD

**Issue by clementgalidie** [taoqf/node-html-parser#81]
Hello!

Since the `v1.4.2`, I encounter this error: `Object prototype may only be an Object or null: undefined`
Here is a screenshot of the stack trace:
![image](https://user-images.githubusercontent.com/5917343/97324473-27eb4300-1872-11eb-8e36-fce2fc7feb68.png)
To be more precise, the following code block generates the error:
```js
var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
```
`b` seems to have `undefined` as a value.

The project I'm working on runs with [Nuxt.js](https://nuxtjs.org/) `v2.14.7` and [Vue.js](https://vuejs.org/) `v2.6.12`.

`node-html-parser` is used in this JavaScript file:
```js
import { parse } from 'node-html-parser';

export default ({app}, inject) => {
  inject('getLazyLoadStream', (options) => {
    const tr = parse(options, {
      lowerCaseTagName: false,
      script: true,
      pre: true,
      comment: false
    })

    for (const img of tr.querySelectorAll('img')) {
      img.setAttribute('data-src', img.getAttribute('src'))
      img.setAttribute('data-sizes', 'auto')
      img.removeAttribute('src')
      img.setAttribute('class', ((img.getAttribute('class') || '') + ' lazyload').trimStart())
    }

    return tr.toString()
  })

  inject('lazyConverter', (data) => {
    return app.$getLazyLoadStream(data)
  })
}

```
I thought the following error was due to some invalid HTML so I tried to get 0 HTML error but that didn't solve the issue.

Before upgrading, I was using the `v1.3.1` of `node-html-parser` and everything worked well.
Do you've ideas about what's happening? :thinking:

**Comment by skennel2** [comment]
Same here

**Comment by younguna** [comment]
same here. went down to 1.3.1 to work again.

**Comment by taoqf** [comment]
Sorry for that. will 1.4.3 work?

**Comment by clementgalidie** [comment]
Hello!

Sorry for the late answer @taoqf!

Thanks for your latest update!
Currently, it works well with `node` `v14.0.0` and `npm` `v6.14.4`.

We did a `Node.js` version downgrade due to several errors with `node` `v.15`

**Comment by taoqf** [comment]
@clementgalidie  I am using `v15.0.1`. What's the errors?

**Comment by taoqf** [comment]
closing as no response.
