### ISSUE TITLE
why use \6 @ matcher.ts line:183?

### ISSUE THREAD

**Issue by tswordyao** [taoqf/node-html-parser#84]
thanks for your lib, very much~

i dont understand the  use "\6" ........  

Can you give a use case? or it can be instead  by other char?

**Comment by taoqf** [comment]
I am so sorry that I can not help you out with such clue. Could you please describe this more clearly?

**Comment by tswordyao** [comment]
https://github.com/taoqf/node-html-parser/blob/master/src/matcher.ts#L183

```
reg = /^\[\s*(\S+)\s*(=|!=)\s*((((["'])([^\6]*)\6))|(\S*?))\]\s*/.exec(tagName);
```

what's the \6  means?

**Comment by taoqf** [comment]
Aha, there must be something wrong.
