### ISSUE TITLE
How to remove current element

### ISSUE THREAD

**Issue by akelmj** [taoqf/node-html-parser#85]
Hi,
I have this code:

` let div =  selector.querySelector("#divid");`

i want to remove the div like:

`div.remove();`

is there any way to do that?

**Comment by taoqf** [comment]
I suppose you are an user of jquery. see [this example](https://github.com/taoqf/node-html-parser/commit/fe5ecaa09e4a63c3b2b554701170d1a9082c31de#diff-60f53864ada74b10948c0d9db8a849c798bb2129290a149b5fa9e802e151b7d8R19), or just use method [remove](https://github.com/taoqf/node-html-parser#htmlelementremove).

**Comment by akelmj** [comment]
thank you for your fast response :+1: 

what if i want to delete an element with out parent:

example:

`<customElement></customElement>
<html>
....
</html>`

in this example if i use the remove method it will NOT work:

`let custom_element = selector.querySelector("customElement");

custom_element.remove();

`

**Comment by taoqf** [comment]
Sorry, I don't get your point. and, what's the example?

**Comment by akelmj** [comment]
the remove() method remove only child element.

example that wok:

<html>
 <custom></custom>
</html>

`let custom_element = selector.querySelector("custom");

custom_element.remove();`


example that NOT work (the custom tag outside the HTML):

 <custom></custom>
<html>

</html>

the same code not remove the custom tag:
`let custom_element = selector.querySelector("custom");

custom_element.remove();`

I hope that i explained well.

**Comment by taoqf** [comment]
Yes, you explained well.
This is not a simple issue, the reason is the element has not get a parent.
Actually, it do has a root node called 'Root', but the element has no parent for most users, see [code](https://github.com/taoqf/node-html-parser/blob/master/src/nodes/html.ts#L878):
```ts
response.childNodes.forEach((node) => {
	if (node instanceof HTMLElement) {
		node.parentNode = null;
	}
});
```
I don't know if we can change some code here, and just make `remove` seems right.

**Comment by taoqf** [comment]
Maybe that will also make sense.

**Comment by taoqf** [comment]
try v2.0.0, good luck!
