### ISSUE TITLE
semver and breaking changes 

### ISSUE THREAD

**Issue by moltar** [taoqf/node-html-parser#87]
Not sure if this package is following SemVer, but there was a breaking change in options, which did not bump the major.

https://github.com/taoqf/node-html-parser/commit/d7a8c292cf81041053ebdcdc7535d084af6c2f89

Thanks.

**Comment by taoqf** [comment]
Maybe, the default value of `script`, `style` and 'pre' changed to `true`.
Then, what should I do now? unpublish v1.3.3?

**Comment by moltar** [comment]
Hm, previously I was using it like this:

```ts
parse(html, { script: true })
```

And now it's like this:

```ts
parse(html, {
    blockTextElements: {
      script: true,
    },
  })
```

So it seems it is more than just a defaults change.

**Comment by taoqf** [comment]
Sorry I didn't get your point, What is the issue now?

**Comment by moltar** [comment]
No issue now, as I have already migrated.

But the issue was this.

When I was using `1.3.0`, the options were:

```ts
parse(html, {
  script: true
})
```

And when I upgraded to `1.4.9`, the options are:

```ts
parse(html, {
    blockTextElements: {
      script: true,
    },
  })
```

That was a breaking change, but the major version was not bumped.

**Comment by taoqf** [comment]
You mean I should set the major version `2`?

**Comment by moltar** [comment]
If you are following SemVer, then yes.

**Comment by taoqf** [comment]
Ah, What should I do now? could you please help me.

**Comment by moltar** [comment]
Well, I think it is too late now. But you can consider that in the future.

**Comment by taoqf** [comment]
OK, thank you very much.

**Comment by moltar** [comment]
Here you can read about SemVer: https://semver.org/

This is not a requirement, but most NPM packages follow that.

**Comment by ajimix** [comment]
Yes please, or at least add CHANGELOG.md with changes so it's easier to upgrade without breaking stuff

**Comment by taoqf** [comment]
Thank you all, I will do it after 2.0
