### ISSUE TITLE
Tags are stripped

### ISSUE THREAD

**Issue by ali-habibzadeh** [taoqf/node-html-parser#91]
When tags are not self closing nor closed the parser just strips them:

```
const html = parse(`
  <head>
  <div>3</div><iframe><p><h1>
  </head>`);
  console.log(html.querySelector("head").innerHTML);
```

Logs:

```
  <div>3</div>
```

Expected: 
```
  <div>3</div>
  <iframe></iframe>
  <p></p>
  <h1></h1>
```

**Comment by taoqf** [comment]
I am so sorry to hear that, but it is designed to be like that.
The result is also not going to be correct even in browser .

**Comment by ali-habibzadeh** [comment]
The browser would be completely different. Browsers correct the DOM and transfer the malformed positioning into correct container which in this case would be BODY. Which browser did you try if I may ask?

**Comment by taoqf** [comment]
I checked the issues again and find this. I do remember I responsed some time ago.
You can try this in chrome:

```js
const div = document.createElement('div');
div.innerHTML = `<head>
  <div>3</div><iframe><p><h1>
  </head>`;
div;
```

you would see the result

```html
<div>
<div>3</div>
<iframe>
"<p><h1>
</head>"
</iframe>
</div>
```

see, that is not you expected either.

I will not do that extra work to slow down the parsing speed for this reason. 

actuall, you could fork ths rep and [do some change here](https://github.com/taoqf/node-html-parser/blob/0d930bb85f0577fbbc5b4cf179e73fb4fbd95456/src/nodes/html.ts#L589) as your wish.

wish you good luck.
