### ISSUE TITLE
CSS child selector or adjacent sibling selector

### ISSUE THREAD

**Issue by blankstar85** [taoqf/node-html-parser#94]
Hello, 

is there a way to only get the first set of matches? I'm trying to select only all of the first set of tr under tbody and not any tr under first set of tr.

html: 
```html
<tbody>
  <tr>
      <tbody>
          <tr>
              more
          </tr>
      </tbody>
  </tr>
  <tr>
      etc
  </tr>
</tbody>

```
 example.querySelectorAll('tbody tr');

I get all 3 tr instead of the upper 2. Is this possible?

I'm able to take a slightly longer route to achieve this
```typescript
  .querySelector('tbody')
  .childNodes.filter((node: HTMLElement) => node.rawTagName === 'tr')
```
just wondering if there is an easier way to accomplish this just using the query selecter. I tried using > tbody > tr as I would a css selector, but no results are returned.

**Comment by taoqf** [comment]
I am afraid the answer is No, not for now.
`querySelector` just could do the **simple** query.

**Comment by blankstar85** [comment]
Thanks. Appreciate the reply.

**Comment by taoqf** [comment]
You are welcome.
