### ISSUE TITLE
add textContent for easier manipulation dom manipulation

### ISSUE THREAD

**Issue by binary-person** [taoqf/node-html-parser#95]
it would be easier if there was a getter/setter instead of going hack mode: finding all the TextNodes, concatenating them into a string, then deleting the entire childNodes and replacing it with a new TextNode.

`element.set_content` won't work as expected as the code tries to parse it as html, which is a problem if the thing being replaced is a text block (for a script tag, for example)

**Comment by taoqf** [comment]
https://www.npmjs.com/package/node-html-parser#htmlelementtextcontent

**Comment by binary-person** [comment]
it works. thank you for taking the time to implement it
